CREATE DATABASE COMPANHIAAEREA;
USE COMPANHIAAEREA;

CREATE TABLE VOO(
NUMVOO INT NOT NULL,
PILOTOVOO VARCHAR(30) NOT NULL,
AEROPARTVOO VARCHAR(25) NOT NULL,
AEROCHEGAVOO VARCHAR(25) NOT NULL,
NUMSERIAVIAO INT NOT NULL
);

INSERT INTO VOO VALUES (1, "ISAAC DOS SANTOS", "PARTIDA", "CHEGADA", 123456);

ALTER TABLE VOO ADD CONSTRAINT PK_VOO PRIMARY KEY (NUMVOO);
ALTER TABLE VOO AND CONSTRAINT FK_AVIAO FOREIGN KEY (NUMAVIAO) REFERENCES AVIAO (NUMAVIAO);

UPDATE VOO 
SET AEROPARTVOO = "Frank Miloye Milenkovich"
WHERE NUMVOO = 1;

CREATE TABLE PASSAGEIRO(
CPF INT NOT NULL,
NOMEPASS VARCHAR(30),
CODASSENTO INT NOT NULL
);

ALTER TABLE PASSAGEIRO ADD CONSTRAINT PK_PASSAGEIRO PRIMARY KEY (CPF);
ALTER TABLE PASSAGEIRO AND CONSTRAINT FK_ASSENTO FOREIGN KEY (CODASSENTO) REFERENCES ASSENTO (CODASSENTO);

CREATE TABLE AVIAO(
NUMAVIAO INT NOT NULL,
MODELOAVIAO VARCHAR(30)
);

INSERT INTO AVIAO VALUES (123456, "boing 737");

ALTER TABLE AVIAO ADD CONSTRAINT PK_AVIAO PRIMARY KEY (NUMAVIAO);

UPDATE AVIAO
SET MODELOAVIAO = "BOEING"
WHERE NUMAVIAO = 123456;

CREATE TABLE ASSENTO(
CODASSENTO INT NOT NULL,
NUMAVIAO VARCHAR(30) NOT NULL
);
ALTER TABLE ASSENTO CHANGE NUMAVIAO NUMAVIAO INT NOT NULL;

ALTER TABLE ASSENTO AND CONSTRAINT PK_ASSENTO PRIMARY KEY (CODASSENTO);
ALTER TABLE ASSENTO AND CONSTRAINT FK_AVIAOASSENTO FOREIGN KEY (NUMAVIAO) REFERENCES AVIAO (NUMAVIAO);

CREATE TABLE ECONOMICO(
CODASSENTO INT NOT NULL,
CODECO INT NOT NULL
);

ALTER TABLE ECONOMICO ADD CONSTRAINT PK_ECONOMICO PRIMARY KEY (CODECO);
ALTER TABLE ASSENTO AND CONSTRAINT FK_ECOASSENTO FOREIGN KEY (CODASSENTO) REFERENCES ASSENTO (CODASSENTO);

CREATE TABLE EXECUTIVO(
CODASSENTO INT NOT NULL,
CODEXE INT NOT NULL
);

ALTER TABLE EXECUTIVO ADD CONSTRAINT PK_EXECUTIVO PRIMARY KEY (CODEXE);
ALTER TABLE ASSENTO AND CONSTRAINT FK_EXEASSENTO FOREIGN KEY (CODASSENTO) REFERENCES ASSENTO (CODASSENTO);


