CREATE DATABASE EMPRESA_LIMPEZA;
USE EMPRESA_LIMPEZA;

CREATE TABLE CLIENTE(
CODCLI INT NOT NULL,
NOMECLI VARCHAR(40),
STATUSCLI VARCHAR(20),
TELCLI VARCHAR(14),
ENDCLI VARCHAR(100),
LIMCREDCLI VARCHAR(20)
);

INSERT INTO CLIENTE VALUES (1, "DAIANA MURADOR", "PAGO", 909099090, "RUA PAULO CENTRONE", 2000.00);
INSERT INTO CLIENTE VALUES (2, "PATRICIA DOS SANTOS", "PAGO", 344567890, "RUA DAS ROSEIRAS", 4000.00);
INSERT INTO CLIENTE VALUES (3, "ROSANA OLIVEIRA", "PAGO", 45678909, "RUA DO ARMANDO", 2500.00);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (CODCLI);

CREATE TABLE PEDIDO(
NUMPED INT NOT NULL,
DATAELABPED VARCHAR(20),
CODCLI INT NOT NULL
);

INSERT INTO PEDIDO VALUES (1, "10/05/2025", 1);
INSERT INTO PEDIDO VALUES (2, "11/11/2025", 2);
INSERT INTO PEDIDO VALUES (3, "17/11/2025", 3);

ALTER TABLE PEDIDO ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (NUMPED);
ALTER TABLE PEDIDO ADD CONSTRAINT FK_CLIENTE FOREIGN KEY (CODCLI) REFERENCES CLIENTE (CODCLI);

CREATE TABLE PRODUTO(
CODPROD INT NOT NULL,
NOMEPROD VARCHAR(20),
PRECOPROD VARCHAR(10)
);

INSERT INTO PRODUTO VALUES (1, "AMACIANTE", "25.90", 1);
INSERT INTO PRODUTO VALUES (2, "SABÃO EM PÓ", "30.90", 2);
INSERT INTO PRODUTO VALUES (3, "DESINFETANTE", "15.90", 3);

ALTER TABLE PRODUTO
ADD CODCAT INT NOT NULL;

ALTER TABLE PRODUTO ADD CONSTRAINT PK_PRODUTO PRIMARY KEY (CODPROD);
ALTER TABLE PRODUTO ADD CONSTRAINT FK_CATEGORIA FOREIGN KEY (CODCAT) REFERENCES CATEGORIA (CODCAT);

CREATE TABLE CATEGORIA(
CODCAT INT NOT NULL,
DESCCAT VARCHAR(20)
);

INSERT INTO CATEGORIA VALUES (1, "PRODUTO CHEIROSO");
INSERT INTO CATEGORIA VALUES (2, "TIRA MANCHAS");
INSERT INTO CATEGORIA VALUES (3, "CHÃO LIMPO");

ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (CODCAT);

CREATE TABLE PEDIDO_PRODUTO(
NUMPED INT NOT NULL,
CODPROD INT NOT NULL,
QTDEITEM VARCHAR(10)
);

INSERT INTO PEDIDO_PRODUTO VALUES (1, 1, 10);
INSERT INTO PEDIDO_PRODUTO VALUES (2, 2, 5);
INSERT INTO PEDIDO_PRODUTO VALUES (3, 3, 10);

ALTER TABLE PEDIDO_PRODUTO MODIFY QTDEITEM INT NOT NULL;

ALTER TABLE PEDIDO_PRODUTO ADD CONSTRAINT PK_PEDIDO_PRODUTO PRIMARY KEY (NUMPED, CODPROD);
ALTER TABLE PEDIDO_PRODUTO ADD CONSTRAINT FK_PEDIDO FOREIGN KEY (NUMPED) REFERENCES PEDIDO (NUMPED);
ALTER TABLE PEDIDO_PRODUTO ADD CONSTRAINT FK_PRODUTO FOREIGN KEY (CODPROD) REFERENCES PRODUTO (CODPROD);

CREATE TABLE PRODUTO_CATEGORA(
CODPROD INT NOT NULL,
CODCAT INT NOT NULL,
QUANITENS VARCHAR(10)
);

DROP TABLE PRODUTO_CATEGORA;

SELECT * FROM CLIENTE;